### ISSUE TITLE
Prepsat do Python3

### ISSUE THREAD

**Issue by vician** [jizdoteka/jizdoteka-web#3]
"Myslím, že by bylo lepší rovnou začít s Pythonem 3, zbytečně bychom museli později přecházet. Python 2 je už jen v maintenance a v roce 2020 mu končí podpora."

**Comment by mpavlase** [comment]
Souhlasím, 4 roky už jsou docela krátká doba.

**Comment by KosiehBarter** [comment]
At take neco delam, rad vypomuzu s prepsanim.

**Comment by vician** [comment]
@KosiehBarter Dostavam `AttributeError: 'module' object has no attribute 'Comment'` - mel jsi to taky?
Tato issue mi prijde dulezitejsi nez ta grafika.

**Comment by KosiehBarter** [comment]
@vician ano, mel.

UPDATE:
models nemaji zadne z Comments, Waypoint apod, jak je definovano v admin.py. Zkusim se podivat a vyresit.

**Comment by KosiehBarter** [comment]
Update: Pull request na #7 .

**Comment by vician** [comment]
Diky @KosiehBarter zaviram.
